In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
import duckdb
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [ ]:
# lendo o arquivo z0019_1.csv e adicionando as colunas nome_arquivo e data_ingestao
# criando um dataframe com os dados do arquivo z0019_1.csv

arquivo='z0019_1.csv'
data_ingestao = datetime.now()

df = pd.read_csv(f'../landing/{arquivo}' , sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-07-30 10:09:05.900232
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-07-30 10:09:05.900232
2  10003     PREGO  BT10    100    500  z0019_1.csv 2026-07-30 10:09:05.900232
3  10004     SERRA  BT50    100    200  z0019_1.csv 2026-07-30 10:09:05.900232
4  10005   MACHADO  BT50    100    100  z0019_1.csv 2026-07-30 10:09:05.900232

In [ ]:
# criando a tabela bronze_produtos caso ela não exista

con.execute('''
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao timestamp       
    )
''')

In [ ]:
# lendo o arquivo z0019_2.csv e adicionando as colunas nome_arquivo e data_ingestao

resultado = con.execute('SELECT * FROM bronze_produtos').fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-30 10:09:05.900232
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-30 10:09:05.900232
2  10003     PREGO  BT10   100   500  z0019_1.csv 2026-07-30 10:09:05.900232
3  10004     SERRA  BT50   100   200  z0019_1.csv 2026-07-30 10:09:05.900232
4  10005   MACHADO  BT50   100   100  z0019_1.csv 2026-07-30 10:09:05.900232

In [ ]:
# inserindo os dados do dataframe na tabela bronze_produtos

con.execute("insert into bronze_produtos select * from df")

In [ ]:
# lendo o arquivo z0019_2.csv e adicionando as colunas nome_arquivo e data_ingestao

arquivo='z0019_2.csv'
data_ingestao = datetime.now()

df = pd.read_csv(f'../landing/{arquivo}' , sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-07-30 10:16:19.439626
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-07-30 10:16:19.439626
2  10003    PREGO  BT10    100    600  z0019_2.csv 2026-07-30 10:16:19.439626

In [12]:
# codigo não fara nada pois cira somente se nao existir a tabela, mas como ja existe, nao fara nada

con.execute('''
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao timestamp       
    )
''')

In [13]:
# vou inserir os dados do arquivo z0019_2.csv na tabela bronze_produtos
con.execute("insert into bronze_produtos select * from df")

In [16]:
# vou ler a tabela bronze_produtos para verificar se os dados foram inseridos corretamente
resultado = con.execute('SELECT * FROM bronze_produtos').fetchdf()
resultado.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-30 10:09:05.900232
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-30 10:09:05.900232
2  10003     PREGO  BT10   100   500  z0019_1.csv 2026-07-30 10:09:05.900232
3  10004     SERRA  BT50   100   200  z0019_1.csv 2026-07-30 10:09:05.900232
4  10005   MACHADO  BT50   100   100  z0019_1.csv 2026-07-30 10:09:05.900232
5  10004     SERRA  BT50   100   200  z0019_2.csv 2026-07-30 10:16:19.439626
6  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-30 10:16:19.439626
7  10003     PREGO  BT10   100   600  z0019_2.csv 2026-07-30 10:16:19.439626

In [17]:
# vamos renomear a tabela bronze_produtos para bronze_z0019
con.execute("alter table bronze_produtos RENAME to bronze_z0019")

In [18]:
# nao existe mais a tabela bronze_produtos, agora existe a tabela bronze_z0019
# a tabela bronze_z0019 agora contem os dados dos arquivos z0019_1.csv e z0019_2.csv
# vamos ler a tabela bronze_z0019 para verificar se os dados foram inseridos corretamente

resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-30 10:09:05.900232
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-30 10:09:05.900232
2  10003     PREGO  BT10   100   500  z0019_1.csv 2026-07-30 10:09:05.900232
3  10004     SERRA  BT50   100   200  z0019_1.csv 2026-07-30 10:09:05.900232
4  10005   MACHADO  BT50   100   100  z0019_1.csv 2026-07-30 10:09:05.900232
5  10004     SERRA  BT50   100   200  z0019_2.csv 2026-07-30 10:16:19.439626
6  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-30 10:16:19.439626
7  10003     PREGO  BT10   100   600  z0019_2.csv 2026-07-30 10:16:19.439626

In [19]:
# fechando a conexão com o banco de dados
con.close()